preload = ~/Pictures/Wallpapers/Ghibli-1.png

wallpaper {
    monitor = eDP-2
    path = ~/Pictures/Wallpapers
    fit_mode = cover
    timeout = 300
    order = random          
    recursive = true        
}